### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by ghs-medilies** [medilies/sheet2pdf#1]
```
❯ php .\sheet2pdf.php .\example\5AP1.xlsx .\example\template.html 4
TypeError: Src\Pdf::Src\{closure}(): Argument #1 ($key) must be of type string, null given in C:\dev\sheet2pdf\Src\Pdf.php:94
Stack trace:
#0 [internal function]: Src\Pdf->Src\{closure}(NULL)
#1 C:\dev\sheet2pdf\Src\Pdf.php(95): array_map(Object(Closure), Array)
#2 C:\dev\sheet2pdf\Src\Pdf.php(74): Src\Pdf->render()
#3 C:\dev\sheet2pdf\Src\Cli.php(73): Src\Pdf->__construct(Array, Array, '5AP1-2022-Jan-2...')
#4 C:\dev\sheet2pdf\vendor\splitbrain\php-cli\src\CLI.php(175): Src\Cli->main(Object(splitbrain\phpcli\Options))
#5 C:\dev\sheet2pdf\vendor\splitbrain\php-cli\src\CLI.php(97): splitbrain\phpcli\CLI->execute()
#6 C:\dev\sheet2pdf\sheet2pdf.php(9): splitbrain\phpcli\CLI->run()
#7 {main}
```

happens with some .xlsx files

**Comment by medilies** [comment]
Possible fix here https://github.com/medilies/sheet2pdf/blob/main/Src/Pdf.php#L95

```php
        // Preparing for bulk replace
        $all_possible_patterns =  array_map(
            function (string|null $key): string {
                if (is_null($key)) {
                    return '';
                }
                return "%VAR_$key%";
            },
            $this->fields
        );
```
